Maintenance scripts finished.

diff --git a/configuration/templates/package/debian/DEBIAN/postinst.tmpl b/configuration/templates/package/debian/DEBIAN/postinst.tmpl
--- a/configuration/templates/package/debian/DEBIAN/postinst.tmpl
+++ b/configuration/templates/package/debian/DEBIAN/postinst.tmpl
@@ -25,40 +25,52 @@ add_user_and_group() {
 }
 
 create_dirs_and_files() {
-	# Create required directories and files.{{if eq .Domain "edge"}}
+	echo -n "Creating required directories and files..."{{if eq .Domain "edge"}}
 	mkdir -p /opt/thingsplex/{{.PackageName}}/data
 	mkdir -p /var/log/thingsplex/{{.PackageName}}
 	touch /var/log/thingsplex/{{.PackageName}}/{{.PackageName}}.log{{else}}
 	mkdir -p /var/log/futurehome/{{.PackageName}}
 	touch /var/log/futurehome/{{.PackageName}}/{{.PackageName}}.log{{end}}
+	echo "...OK"
 }
 
 set_ownership() {
-	# Set proper ownership and rights for files.{{if eq .Domain "edge"}}
+	echo -n "Set proper ownership and rights for files..."{{if eq .Domain "edge"}}
 	chown -R {{.PackageName}}:thingsplex /opt/thingsplex/{{.PackageName}} || true
 	chown -R {{.PackageName}}:thingsplex /var/log/thingsplex/{{.PackageName}} || true
-	chmod -R 644 /var/log/thingsplex/{{.PackageName}} || true
-	chmod -R 644 /opt/thingsplex/{{.PackageName}}/defaults || true{{else}}
+	chmod 644 /opt/thingsplex/{{.PackageName}}/defaults/* || true
+	chmod 644 /opt/thingsplex/{{.PackageName}}/VERSION
+	chmod 644 /var/log/thingsplex/{{.PackageName}}/* || true{{else}}
 	chown -R {{.PackageName}}:futurehome /var/lib/futurehome/{{.PackageName}} || true
 	chown -R {{.PackageName}}:futurehome /var/log/futurehome/{{.PackageName}} || true
-	chmod -R 644 /var/log/futurehome/{{.PackageName}} || true
-	chmod -R 644 /etc/futurehome/{{.PackageName}} || true{{end}}
+	chmod 644 /var/log/futurehome/{{.PackageName}}/* || true
+	chmod 644 /etc/futurehome/{{.PackageName}}/* || true
+	chmod 644 /var/lib/futurehome/{{.PackageName}}/* || true{{end}}
+	echo "...OK"
 }
 
 configure_service() {
-		# Revert service to the previously recorded state.
-		deb-systemd-helper unmask {{.PackageName}}.service >/dev/null
-		# Enable service on the first installation.
-		deb-systemd-helper enable {{.PackageName}}.service >/dev/null
-		# Start service if it is enabled.
-		if deb-systemd-helper --quiet is-enabled {{.PackageName}}.service; then
-			deb-systemd-invoke start {{.PackageName}}.service > /dev/null
+		echo -n "Configuring service..."
+		systemctl enable {{.PackageName}}.service > /dev/null || true
+		systemctl --system daemon-reload >/dev/null || true
+		systemctl start {{.PackageName}}.service > /dev/null || true
+		{{/* Following is a proper solution using deb-systemd-helper:
+		deb-systemd-helper unmask zombie-attack.service >/dev/null
+		deb-systemd-helper enable zombie-attack.service >/dev/null
+		if deb-systemd-helper --quiet was-enabled zombie-attack.service; then
+			deb-systemd-helper reenable zombie-attack.service >/dev/null
+		else
+			deb-systemd-helper update-state zombie-attack.service >/dev/null
 		fi
+		if deb-systemd-helper --quiet is-enabled zombie-attack.service; then
+			deb-systemd-invoke start zombie-attack.service > /dev/null
+		fi
+		*/}}
+		echo "...OK"
 }
 
 case "$1" in
 	configure)
-	  echo "Configuring..."
 		add_user_and_group
 		create_dirs_and_files
 		set_ownership
